### ISSUE TITLE
框选范围错误

### ISSUE THREAD

**Issue by zhylmzr** [myliang/x-spreadsheet#109]
3个紧邻的合并单元格，选取上方两个后选区错误，正常应该是三个单元格都被选中
![Snipaste_2019-04-16_02-45-26](https://user-images.githubusercontent.com/15730824/56157293-b92cf880-5ff1-11e9-8729-c4effe7130ce.png)

**Comment by myliang** [comment]
fixed it, update last version

**Comment by zhylmzr** [comment]
The bug still exists

<img width="436" alt="Snipaste_2019-05-07_10-47-07" src="https://user-images.githubusercontent.com/15730824/57268188-7bcdff00-70b5-11e9-91d9-7db59c053b25.png">
